name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install required dependencies
        run: npm install

      - name: Run Format Check
        run: npm run format
        
      - name: Run lint
        run: npm run lint

      

      - name: Check Commit message
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.ts
