name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.26

      - name: Install required dependencies
        run: bun install

      - name: Run Format Check
        run: bun run format
        
      - name: Run lint
        run: bun run lint

      

      - name: Check Commit message
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.ts
